# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vaHkLdOrVqCGxdNRPWn1H8A7TAYs7KI2
"""

#list 
l=[3,7,31,3,72,61,25]
print(l[2])     #to access elements in the list by using index values
print(len(l))   #to print number of elements in the list
l.append(45)    #to add elements in the list
print(l)
m=[4,45,9,21,33,63]
l.extend(m)     #to append a list to the list 
print(l)
l.sort()        #to sort the list
print(l)
l.insert(2,43)  #to insert an element in the list 
print(l)
l.pop(1)        #to delete an element by using index values
print(l)
l.remove(21)    #to delete an element by using element in parenthesis brackets
print(l)
del l[1:5]      #to delete certain range of elements 
print(l)
l.count(45)     #returns the number of times an element appear in the list
print(l)
list=[2,12,32,18,7]
print(max(list))     #prints the maximum element
print(len(list))     #prints the length of the list
print(min(list))     #prints th minimum element
print(sum(list))     #prints the sum of all the elements in the list



a = [1, 21, 33]
b = [45, 54, 63]
c = a + b
print(c)
print(a*2)
print(c[1:4])     #slice operations
print(c[1:])
print(c[:3])
a[2]=45
print(a)

a=('t','u','p','l','e')
b=('o','p','e','r','a','t','i','o','n','s')
print(a+b)               #concatenation
print(a*2)
print(a)
print('t' in a)
print('b' in b)          #membership tests

a=('a','y','r','a')
print(a*2)
print(a[1:3])    
print(a[-3:])
print(a[:3])
print(a[:])

d={'name':'ron','age':22}
print(d['name'])
print(d['age'])
print(d.get('name'))
print(d.get('address'))               #returns none if the key is not found in the dictionary
d['address']='downtown'               #to add the element
print(d)
d['age']=26                           #to update the value
print(d.pop('address'))
print(d)
print(d.popitem())
print(d)
d.clear()
print(d)

a={1:45,2:63,3:33,4:32}
b={1:7,2:18,3:54,4:20}
print(sorted(a))
print(b.values())
print(a.keys())
print(b.items())

set1={"python",45,345.6,"temp"}
set2={"variable",43,43.50}
print(set1.union(set2))
print(set1.intersection(set2))          #returns set() if no element is in common
set1.add("program")
print(set1)

a={"white","black","green","yellow"}
b={"white","yellow","orange","brown"}
print(a.difference(b))
print(b.difference(a))